#!/bin/sh


if [ -x /usr/local/bin/brew ];
then
    echo "Skipping install of brew. It is already installed.";
    echo "Updating brew..."
    brew update;
    echo "Updated brew."
else
    echo "Installing brew...";
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
    if [ -x /usr/local/bin/brew ];
    then
        echo "Installed brew";
    else
        exit 1;
    fi
fi

echo "Running brew bundle...";

brew bundle;

echo "brew bundle complete";

# do some ruby specific stuff
RUBY_VERSION=2.5.1
echo "🦄  ruby" $RUBY_VERSION
rbenv install -s $RUBY_VERSION
rbenv global $RUBY_VERSION

# bash-it
# if [ -x ~/.bash_it/install.sh ];
# then
#   echo "Skipping install of bash-it, since it's already installed.";
# else
#   git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
#   ~/.bash_it/install.sh
# fi

if [ -x ~/.vimrc ];
then
  echo "Skipping vim config, since .vimrc already exists.";
else
  curl -s 'http://vim-bootstrap.com/generate.vim' --data 'langs=javascript&langs=php&langs=html&langs=ruby&langs=go&editor=vim' > ~/.vimrc
fi


echo "Setup complete";
